import React from "react";
import Head from "next/head";
import {
  Button,
  VStack,
  HStack,
  Text,
  IconButton,
  Heading,
  Wrap,
  useColorModeValue,
} from "@chakra-ui/react";
import PageTransition from "../components/page-transitions";
import Section from "@/components/section";
import interests from "../data/interests.json";
import experience from "../data/experience.json";
import InterestTag from "@/components/interest-tag";
import ExperienceCard from "@/components/experience-card";
import Hero from "@/components/hero";
import Link from "@/components/link";
import Layout from "@/layouts/layout";

const About = () => (
  <Layout>
    <Hero title="About" align="start" subtitle="Learn more about me" />
    <VStack spacing={12} mt={6}>
      <Section>
        <VStack align="start" spacing={6}>
          <Text>
            I'm a designer, developer, and maker of sorts. I'm an all-around
            curious person who can't get enough of exploring new ideas and
            asking lots of questions.
          </Text>
          <Text>
            In my free time, you can usually find me reading books, cooking,
            playing board games, outside with the bicycle or simply spending
            time with those closest to me.
          </Text>
          <Text>
            I'm an advocate for working and learning in public, which I'm doing
            on and off on on{" "}
            <Link href="https://www.linkedin.com/in/wirtzdan/">LinkedIn</Link>,
            <Link href="https://x.com/wirtzdan"> X</Link>,{" "}
            <Link href="https://bsky.app/profile/danielwirtz.com">Bluesky</Link>{" "}
            and my{" "}
            <Link href="https://www.youtube.com/@wirtzdan">
              YouTube channel
            </Link>
            .
          </Text>
          <VStack
            bg={useColorModeValue("blue.50", "blue.900")}
            p={4}
            borderRadius="lg"
            borderColor={useColorModeValue("blue.200", "blue.700")}
            borderWidth="1px"
          >
            <Text>
              I'm currently looking for new opportunities. If you want to chat,
              <Link href="mailto:daniel@danielwirtz.com">
                {" "}
                feel free to reach out to me.{" "}
              </Link>
            </Text>
          </VStack>
        </VStack>
      </Section>

      <Section>
        <VStack align="start" spacing={8}>
          <Heading as="h2" size="lg">
            Experience
          </Heading>
          <VStack align="start" spacing={12} width="100%">
            {experience.experience.map((exp, index) => (
              <ExperienceCard key={index} {...exp} />
            ))}
          </VStack>
        </VStack>
      </Section>

      <Section>
        <VStack align="start" spacing={4}>
          <Heading as="h2" size="lg">
            Like 😁
          </Heading>
          <Wrap>
            {interests.like.map((el) => (
              <InterestTag name={el} like />
            ))}
          </Wrap>
        </VStack>
      </Section>
      <Section>
        <VStack align="start" spacing={4}>
          <Heading as="h2" size="lg">
            Dislike 😒
          </Heading>
          <Wrap>
            {interests.dislike.map((el) => (
              <InterestTag name={el} />
            ))}
          </Wrap>
        </VStack>
      </Section>

      <Section>
        <VStack align="start" spacing={6}>
          <Heading as="h2" size="lg">
            About this page
          </Heading>
          <Text>
            Everything you see here I have designed and built myself. The
            website is using <Link href="https://reactjs.org">React</Link> and{" "}
            <Link href="https://chakra-ui.com">Chakra UI</Link> as a design
            system. The pages are generated by{" "}
            <Link href="https://nextjs.org">NextJS</Link> and are hosted on{" "}
            <Link href="https://vercel.com/">Vercel</Link>.
          </Text>
          <Text>
            The content for the website, such as articles, books and bookmarks
            are stored on{" "}
            <Link href="https://airtable.com/invite/r/HsvqbADg">Airtable</Link>{" "}
            and then pulled in through their API endpoint. If you are curious,
            you can{" "}
            <Link href="https://github.com/wirtzdan/website">
              explore the code for this website
            </Link>{" "}
            on my Github.
          </Text>
        </VStack>
      </Section>
    </VStack>
  </Layout>
);

export default About;
