import { Heading, Text, VStack, Wrap } from "@chakra-ui/react";

import interests from "@/data/interests.json";
import experience from "@/data/experience.json";
import ExperienceCard from "@/components/experience-card";
import Hero from "@/components/hero";
import InterestTag from "@/components/interest-tag";
import Layout from "@/layouts/layout";
import Link from "@/components/link";
import Section from "@/components/section";

const AboutPage = () => {
  return (
    <Layout>
      <Hero title="About" align="start" subtitle="Learn more about me" />
      <VStack spacing={12} mt={6}>
        <Section>
          <VStack align="start" spacing={6}>
            <Text>
              I&apos;m an all-around curious person who can&apos;t get enough of exploring new ideas
              and asking lots of questions.
            </Text>
            <Text>
              In my free time, you can usually find me reading books, cooking, playing board games,
              outside with the bicycle or simply spending time with those closest to me.
            </Text>
            <Text>
              I&apos;m an advocate for working and learning in public, which I&apos;m doing on and
              off on on <Link href="https://www.linkedin.com/in/wirtzdan/">LinkedIn</Link>,{" "}
              <Link href="https://x.com/wirtzdan">X</Link>,{" "}
              <Link href="https://bsky.app/profile/danielwirtz.com">Bluesky</Link> and my{" "}
              <Link href="https://www.youtube.com/@wirtzdan">YouTube channel</Link>.
            </Text>
          </VStack>
        </Section>

        <Section>
          <VStack align="start" spacing={8}>
            <Heading as="h2" size="lg">
              Experience
            </Heading>
            <VStack align="start" spacing={12} width="100%">
              {experience.experience.map((entry) => (
                <ExperienceCard key={`${entry.company}-${entry.role}`} {...entry} />
              ))}
            </VStack>
          </VStack>
        </Section>

        <Section>
          <VStack align="start" spacing={4}>
            <Heading as="h2" size="lg">
              Like 😁
            </Heading>
            <Wrap>
              {interests.like.map((interest) => (
                <InterestTag key={interest} name={interest} like />
              ))}
            </Wrap>
          </VStack>
        </Section>

        <Section>
          <VStack align="start" spacing={4}>
            <Heading as="h2" size="lg">
              Dislike 😒
            </Heading>
            <Wrap>
              {interests.dislike.map((interest) => (
                <InterestTag key={interest} name={interest} />
              ))}
            </Wrap>
          </VStack>
        </Section>

        <Section>
          <VStack align="start" spacing={6}>
            <Heading as="h2" size="lg">
              About this page
            </Heading>
            <Text>
              Everything you see here I have designed and built myself. The website is using{" "}
              <Link href="https://reactjs.org">React</Link> and{" "}
              <Link href="https://chakra-ui.com">Chakra UI</Link> as a design system. The pages are
              generated by <Link href="https://nextjs.org">NextJS</Link> and are hosted on{" "}
              <Link href="https://vercel.com/">Vercel</Link>.
            </Text>
            <Text>
              The content for the website, such as articles, books and bookmarks are stored on{" "}
              <Link href="https://airtable.com/invite/r/HsvqbADg">Airtable</Link> and then pulled in
              through their API endpoint. If you are curious, you can{" "}
              <Link href="https://github.com/wirtzdan/website">
                explore the code for this website
              </Link>{" "}
              on my Github.
            </Text>
          </VStack>
        </Section>
      </VStack>
    </Layout>
  );
};

export default AboutPage;
